# docker build -t factual_reasoning/passage_retrieval:dummay .


# docker run --gpus all --rm -d -it -p 12345:5000 --name passage_retrieval factual_reasoning/passage_retrieval:dummay
# or if you use nvidia-docker
# nvidia-docker run --rm -d -it -p 12345:5000 --name passage_retrieval factual_reasoning/passage_retrieval:dummay

FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime
LABEL maintainer "POSTECH deokhk <deokhk@postech.ac.kr>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y gnupg2
RUN apt-key del 3bf863cc
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion locales rsync \
    libc6 libstdc++6 tar curl net-tools apt-utils
    
RUN locale-gen en_US.UTF-8 && update-locale

ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US:en

ADD app /root/app

WORKDIR /root/app

RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_lg

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]

ENV SERVICE_PORT 5000
EXPOSE ${SERVICE_PORT}