# docker build -t factual_reasoning/passage_retrieval .

# docker tag factual_reasoning/passage_retrieval 10.0.0.161:5000/passage_retrieval
# docker push 10.0.0.161:5000/passage_retrieval

# docker run --gpus all --rm -d -it -p 12345:5000 --name passage_retrieval factual_reasoning/passage_retrieval
# or if you use nvidia-docker
# nvidia-docker run --rm -d -it -p 12345:5000 --name passage_retrieval factual_reasoning/passage_retrieval

# docker -H 10.0.0.110:2375 run --gpus all --rm -d -it --network="dockernet" --ip="10.1.92.121" --name passage_retrieval 10.0.0.161:5000/passage_retrieval

# port: ketiair.com:10021 --> 10.1.92.121:5000

FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
LABEL maintainer "KETI AIRC sankim <kimsan0622@keti.re.kr>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion locales rsync \
    libc6 libstdc++6 python-minimal tar curl net-tools apt-utils

RUN locale-gen en_US.UTF-8 && update-locale

ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US:en

RUN pip install flask 
RUN pip install transformers
RUN pip install faiss-gpu sentencepiece "protobuf<=3.20.0"

ADD app /root/app

WORKDIR /root/app

# download move weights of model and move it to the ./app directory for fast build
# comment below script after above action
RUN cd /root/app && \
    python download_file_from_google_drive.py https://drive.google.com/file/d/1d8FgJPZ5my-VAdyd7HPQoWzzCP1FGSg9/view?usp=sharing T5EncoderSimpleMomentumRetriever_ket5-base-ko-0929_weights.tgz && \
    tar xvzf T5EncoderSimpleMomentumRetriever_ket5-base-ko-0929_weights.tgz && \
    python download_file_from_google_drive.py https://drive.google.com/file/d/1VR3npo-Th3mA0Dfw-_L0aB1yXIr3UJx6/view?usp=sharing T5EncoderSimpleMomentumRetriever_ket5-base-en_weights.tgz && \
    tar xvzf T5EncoderSimpleMomentumRetriever_ket5-base-en_weights.tgz && \
    python download_file_from_google_drive.py https://drive.google.com/file/d/126DTkbvH34hw_UQjoYKz78MceiskcNOb/view?usp=share_link T5MeanBiEncoderRetriever_ket5-base-law-kr_weights.tgz && \
    tar xvzf T5MeanBiEncoderRetriever_ket5-base-law-kr_weights.tgz


CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]


ENV SERVICE_PORT 5000
EXPOSE ${SERVICE_PORT}