set_model:
	cd app/ &&\
	python download_file_from_google_drive.py https://drive.google.com/file/d/1vCV5vLsbbRvyNIfMMpUTnxAn8cuyc8Li/view?usp=sharing model.tar.gz &&\
	tar -zxvf model.tar.gz &&\
	rm model.tar.gz
