# docker build -t factual_reasoning/passage_retrieval:dummay .

# docker tag factual_reasoning/passage_retrieval:dummay 10.0.0.161:5000/passage_retrieval:dummay
# docker push 10.0.0.161:5000/passage_retrieval:dummay

# docker run --gpus all --rm -d -it -p 12345:5000 --name passage_retrieval factual_reasoning/passage_retrieval:dummay
# or if you use nvidia-docker
# nvidia-docker run --rm -d -it -p 12345:5000 --name passage_retrieval factual_reasoning/passage_retrieval:dummay

# docker -H 10.0.0.110:2375 run --gpus all --rm -d -it --network="dockernet" --ip="10.1.92.121" --name passage_retrieval 10.0.0.161:5000/passage_retrieval:dummay

# port: airckeit.iptime.org:10021 --> 10.1.92.121:5000

FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel
LABEL maintainer "KETI AIRC sankim <kimsan0622@keti.re.kr>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion locales rsync \
    libc6 libstdc++6 python-minimal tar curl net-tools apt-utils

RUN locale-gen en_US.UTF-8 && update-locale

ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US:en

RUN pip install flask

ADD app /root/app

WORKDIR /root/app

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]

ENV SERVICE_PORT 5000
EXPOSE ${SERVICE_PORT}